
spring:
  application:
    name: rocketmq-consumer
  cloud:
    stream:
      bindings:
        input1:
          content-type: text/plain
          destination: test-topic1
          group: test-group1
        input2:
          consumer:
            concurrency: 20
            maxAttempts: 1
          content-type: text/plain
          destination: test-topic2
          group: test-group2
      rocketmq:
        binder:
          name-server: 192.168.174.134:9876
        bindings:
          input1:
            consumer:
              orderly: true
          input2:
            consumer:
              orderly: false
              # 只接收tagStr标签的
#              tags: tagStr
server:
  port: 7745
